name: flutter_txms
description: A Flutter package for encoding and decoding hex messages for TxMS transport
version: 0.1.3
repository: https://github.com/bchainhub/flutter_txms
homepage: https://github.com/bchainhub/flutter_txms
documentation: https://github.com/bchainhub/flutter_txms#readme
issue_tracker: https://github.com/bchainhub/flutter_txms/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.29.1"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Keywords related to the package
topics:
  - txms
  - hex
  - sms
  - mms
  - communication

# Funding links
funding:
  - https://github.com/sponsors/bchainhub
  - https://blockindex.net/address/cb7147879011ea207df5b35a24ca6f0859dcfb145999

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
