/// Countries in each group share the same international calling code.
const List<List<String>> callingCodeGroups = [
  [
    'us',
    'ca',
    'do',
    'pr',
    'jm',
    'tt',
    'bs',
    'bb',
    'lc',
    'gd',
    'vc',
    'ag',
    'vi',
    'ky',
    'bm',
    'gu',
    'kn',
    'dm',
    'sx',
    'tc',
    'vg',
    'mp',
    'as',
    'ai',
    'ms',
  ],
  ['ru', 'kz'],
  ['it', 'va'],
  ['gb', 'gg', 'im', 'je'],
  ['no', 'sj'],
  ['fi', 'ax'],
  ['gp', 'mf', 'bl'],
  ['bq', 'cw'],
  ['au', 'cc', 'cx'],
  ['re', 'yt'],
  ['ma', 'eh'],
];

/// European Union members ordered by population, largest first.
const List<List<String>> europeanUnionGroups = [
  [
    'de',
    'fr',
    'it',
    'es',
    'pl',
    'ro',
    'nl',
    'be',
    'cz',
    'pt',
    'se',
    'gr',
    'hu',
    'at',
    'bg',
    'dk',
    'fi',
    'sk',
    'ie',
    'hr',
    'lt',
    'si',
    'lv',
    'ee',
    'cy',
    'lu',
    'mt',
  ],
];

/// European Free Trade Association members ordered by population.
const List<List<String>> europeanFreeTradeAssociationGroups = [
  ['ch', 'no', 'is', 'li'],
];

/// Non-EU European Economic Area members ordered by population.
const List<List<String>> europeanEconomicAreaGroups = [
  ['no', 'is', 'li'],
];

/// Western Balkans Six members ordered by population.
const List<List<String>> westernBalkansSixGroups = [
  ['rs', 'al', 'ba', 'mk', 'xk', 'me'],
];

/// Other organization members ordered by population, largest first.
const List<List<String>> organizationGroups = [
  ['id', 'ph', 'vn', 'th', 'mm', 'my', 'kh', 'la', 'sg', 'tl', 'bn'],
  ['sa', 'ae', 'om', 'kw', 'qa', 'bh'],
  ['br', 'ar', 'bo', 'py', 'uy'],
  ['in', 'pk', 'bd', 'af', 'lk', 'np', 'bt', 'mv'],
  [
    'ht',
    'jm',
    'tt',
    'gy',
    'sr',
    'bz',
    'bs',
    'bb',
    'lc',
    'gd',
    'vc',
    'ag',
    'dm',
    'kn',
    'ms',
  ],
  [
    'ng',
    'et',
    'eg',
    'cd',
    'tz',
    'za',
    'ke',
    'ug',
    'sd',
    'dz',
    'ao',
    'ma',
    'gh',
    'mz',
    'mg',
    'ci',
    'cm',
    'ne',
    'bf',
    'ml',
    'mw',
    'zm',
    'td',
    'so',
    'sn',
    'zw',
    'gn',
    'rw',
    'bj',
    'bi',
    'tn',
    'ss',
    'tg',
    'sl',
    'ly',
    'cg',
    'lr',
    'cf',
    'mr',
    'er',
    'na',
    'gm',
    'bw',
    'ga',
    'ls',
    'gw',
    'gq',
    'mu',
    'sz',
    'dj',
    'km',
    'cv',
    'st',
    'sc',
    'eh',
  ],
];
